@startuml
entity "Meta" {
    +fine: €1.2 billion
    +reason: violating EU privacy laws
}

entity "European Union Regulators" {
    +announcement: statement
}

entity "Facebook" {
    +data: personal data of users
}

entity "Irish Data Protection Commission" {
    +role: chief regulator
}

entity "General Data Protection Regulation" {
    +chapter: Chapter 5
    +conditions: transfer of personal data
}

Meta o-> "European Union Regulators" : fined by
"European Union Regulators" o-> "Facebook" : inquiry into
"Irish Data Protection Commission" o-> Meta : oversees
"General Data Protection Regulation" o-> "Meta" : contravened by
"General Data Protection Regulation" o-> "Facebook" : conditions set for transfer
@enduml